

const cards=[
 {
    id:1,
    category:"Waxing",
  imageURL:"logo.PNG",
  name:"legs",
  description:"description1",
  duration:60,
  price:300,
  max_recipients:"max1",
  location_requirements:"loco1",
  
 },
 {
    id:2,
    imageURL:"logo.PNG",
    name:"service2",
    description:"description2",
    duration:"duration2",
    price:"price2",
    max_recipients:"max2",
    location_requirements:"loco2"
   },
   {
    id:3,
    imageURL:"logo.PNG",
    name:"service3",
    description:"description3",
    duration:"duration3",
    price:"price3",
    max_recipients:"max3",
    location_requirements:"loco3"
   },
   {
    id:4,
    category:"Waxing",
    imageURL:"logo.PNG",
    name:"arms",
    description:"description4",
    duration:90,
    price:200,
    max_recipients:"max4",
    location_requirements:"loco4",
    
   },
   {
    id:1,
  imageURL:"logo.PNG",
  name:"service1",
  description:"description1",
  duration:"duration1",
  price:"price1",
  max_recipients:"max1",
  location_requirements:"loco1"
 },
 {
    id:2,
    imageURL:"logo.PNG",
    name:"service2",
    description:"description2",
    duration:"duration2",
    price:"price2",
    max_recipients:"max2",
    location_requirements:"loco2"
   },
   {
    id:3,
    imageURL:"logo.PNG",
    name:"service3",
    description:"description3",
    duration:"duration3",
    price:"price3",
    max_recipients:"max3",
    location_requirements:"loco3"
   },
   {
    id:4,
    imageURL:"logo.PNG",
    name:"service4",
    description:"description4",
    duration:"duration4",
    price:"price4",
    max_recipients:"max4",
    location_requirements:"loco4"
   },
   {
      id:2,
      imageURL:"logo.PNG",
      name:"service2",
      description:"description2",
      duration:"duration2",
      price:"price2",
      max_recipients:"max2",
      location_requirements:"loco2"
     },
     {
      id:3,
      category:"Waxing",
      imageURL:"logo.PNG",
      name:"full body",
      description:"description3",
      duration:30,
      price:500,
      max_recipients:"max3",
      location_requirements:"loco3",
    
     },
     {
      id:4,
      imageURL:"logo.PNG",
      name:"service4",
      description:"description4",
      duration:"duration4",
      price:"price4",
      max_recipients:"max4",
      location_requirements:"loco4"
     },
     {
      id:1,
    imageURL:"logo.PNG",
    name:"service1",
    description:"description1",
    duration:"duration1",
    price:"price1",
    max_recipients:"max1",
    location_requirements:"loco1"
   },
   {
      id:2,
      imageURL:"logo.PNG",
      name:"half leg",
      description:"description2",
      duration:45,
      price:150,
      category:"Waxing",
      max_recipients:"max2",
      location_requirements:"loco2"
     },
     {
      id:3,
      imageURL:"logo.PNG",
      name:"service3",
      description:"description3",
      duration:"duration3",
      price:"price3",
      max_recipients:"max3",
      location_requirements:"loco3"
     },
     {
      id:4,
      imageURL:"logo.PNG",
      name:"service4",
      description:"description4",
      duration:"duration4",
      price:"price4",
      max_recipients:"max4",
      location_requirements:"loco4"
     }
   
   
  ]
  export default cards;